describe("htmlDisplayDraw test",function(){

	it("htmlDisplayDraw should match test", function(){

		var jsontestInput = '{"orderList": [{"itemName": "Beers", "orderedBy": "Mike", "quantity": 3}, {"itemName": "Balloons", "orderedBy": "Julia", "quantity": 9}, {"itemName": "Chips", "orderedBy": "Jessica", "quantity": 6}, {"itemName": "Beers", "orderedBy": "Julia", "quantity": 1}, {"itemName": "Balloons", "orderedBy": "teees", "quantity": "3"}, {"itemName": "Balloons", "orderedBy": "test", "quantity": "4"}, {"itemName": "Balloons", "orderedBy": "reeeee", "quantity": "2"}, {"itemName": "Balloons", "orderedBy": "tesssaa", "quantity": "6"}], "stateCode": 4}'
		var jsontestOutput = "<div class='orderPanel panelGreen' style='margin: 25px; padding:5px;'><div><p class='panelFont' style='padding-left: 15px;'> Beers</p></div> <div class='panelFont rightText' style='padding-right: 15px;'><p>3  </p> </div><div><p class='panelFont' style='padding-left: 15px;'> Ordered By: <b>Mike</b></p></div></div> <div class='orderPanel panelOrange' style='margin: 25px; padding:5px;'><div><p class='panelFont' style='padding-left: 15px;'> Balloons</p></div> <div class='panelFont rightText' style='padding-right: 15px;'><p>9  </p> </div><div><p class='panelFont' style='padding-left: 15px;'> Ordered By: <b>Julia</b></p></div></div> <div class='orderPanel panelYellow' style='margin: 25px; padding:5px;'><div><p class='panelFont' style='padding-left: 15px;'> Chips</p></div> <div class='panelFont rightText' style='padding-right: 15px;'><p>6  </p> </div><div><p class='panelFont' style='padding-left: 15px;'> Ordered By: <b>Jessica</b></p></div></div> <div class='orderPanel panelGreen' style='margin: 25px; padding:5px;'><div><p class='panelFont' style='padding-left: 15px;'> Beers</p></div> <div class='panelFont rightText' style='padding-right: 15px;'><p>1  </p> </div><div><p class='panelFont' style='padding-left: 15px;'> Ordered By: <b>Julia</b></p></div></div> <div class='orderPanel panelOrange' style='margin: 25px; padding:5px;'><div><p class='panelFont' style='padding-left: 15px;'> Balloons</p></div> <div class='panelFont rightText' style='padding-right: 15px;'><p>3  </p> </div><div><p class='panelFont' style='padding-left: 15px;'> Ordered By: <b>teees</b></p></div></div> <div class='orderPanel panelOrange' style='margin: 25px; padding:5px;'><div><p class='panelFont' style='padding-left: 15px;'> Balloons</p></div> <div class='panelFont rightText' style='padding-right: 15px;'><p>4  </p> </div><div><p class='panelFont' style='padding-left: 15px;'> Ordered By: <b>test</b></p></div></div> <div class='orderPanel panelOrange' style='margin: 25px; padding:5px;'><div><p class='panelFont' style='padding-left: 15px;'> Balloons</p></div> <div class='panelFont rightText' style='padding-right: 15px;'><p>2  </p> </div><div><p class='panelFont' style='padding-left: 15px;'> Ordered By: <b>reeeee</b></p></div></div> <div class='orderPanel panelOrange' style='margin: 25px; padding:5px;'><div><p class='panelFont' style='padding-left: 15px;'> Balloons</p></div> <div class='panelFont rightText' style='padding-right: 15px;'><p>6  </p> </div><div><p class='panelFont' style='padding-left: 15px;'> Ordered By: <b>tesssaa</b></p></div></div>";

		console.log(htmlDisplayDraw(jsontestInput));
		expect(htmlDisplayDraw(jsontestInput).trim()==jsontestOutput.trim()).toBe(true);

	})

});



